name: twitterapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0
environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.7.2
  image_picker: ^1.1.2
  shared_preferences: ^2.2.3
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:  ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/akuntwt.jpg
    - assets/konten.jpg
    - assets/konten2.jpeg
    - assets/konten3.jpg
    - assets/profil.jpg
    - assets/profil2.jpg
    - assets/comment.svg
    - assets/repeat.svg
    - assets/like.svg
    - assets/impressions.svg
    - assets/xlogo.svg